### ISSUE TITLE
There are paper about you work?

### ISSUE THREAD

**Issue by nebula-beta** [AIBluefisher/EGSfM#3]
There are paper about you work?  I want know some detail about you work。

**Comment by AIBluefisher** [comment]
Since our work has been rejected in `CVPR 2019`, we decide to submit to `Pattern Recognition 2020`. As the process of a journal review is slow, we are considering submit it to arXiv in December. Besides, I'm pushing this work to more large scale and robust pipeline while in quite different code base. And we're trying to submit a paper to `ECCV 2020`. You could focus on our work.
